language: cpp
sudo: required
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-devtools yast2-testsuite yast2-core-dev yast2 yast2-network yast2-transfer" -g "rspec:3.3.0 yast-rake gettext rubocop:0.41.2 simplecov coveralls cheetah"
script:
    - rake check:syntax
    - rake check:pot
    - rubocop -c rubocop_yast_style.yml
    - COVERAGE=1 rake test
